//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSync.AppResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSync.AppResources.Localization.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSync.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string btnSuspend {
            get {
                return ResourceManager.GetString("btnSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string btnTestConnection {
            get {
                return ResourceManager.GetString("btnTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string capError {
            get {
                return ResourceManager.GetString("capError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom name.
        /// </summary>
        public static string colCustomName {
            get {
                return ResourceManager.GetString("colCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string colLogin {
            get {
                return ResourceManager.GetString("colLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string colServerName {
            get {
                return ResourceManager.GetString("colServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string colSuspended {
            get {
                return ResourceManager.GetString("colSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnumAppLanguageEnglish {
            get {
                return ResourceManager.GetString("EnumAppLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string EnumAppLanguagePolish {
            get {
                return ResourceManager.GetString("EnumAppLanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string enumServerGoogle {
            get {
                return ResourceManager.GetString("enumServerGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string ErrorFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0};{1};{2};{3};{4};.
        /// </summary>
        public static string ErrorLogFormat {
            get {
                return ResourceManager.GetString("ErrorLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;Message;Exception;Stack trace;Source;.
        /// </summary>
        public static string ErrorLogHeaders {
            get {
                return ResourceManager.GetString("ErrorLogHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to serialize the null object..
        /// </summary>
        public static string exJSonArgumentNullException {
            get {
                return ResourceManager.GetString("exJSonArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connot log null value of exception..
        /// </summary>
        public static string exLogNullException {
            get {
                return ResourceManager.GetString("exLogNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality is currently not available..
        /// </summary>
        public static string exNotImplementedException {
            get {
                return ResourceManager.GetString("exNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is null or empty..
        /// </summary>
        public static string exPropertyNullException {
            get {
                return ResourceManager.GetString("exPropertyNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA private key used to decrypt is empty..
        /// </summary>
        public static string exRsaPrivateKeyIsNull {
            get {
                return ResourceManager.GetString("exRsaPrivateKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string lblAppLanguage {
            get {
                return ResourceManager.GetString("lblAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Name :.
        /// </summary>
        public static string lblCustomName {
            get {
                return ResourceManager.GetString("lblCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login :.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server :.
        /// </summary>
        public static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key saved in the {0} file has errors. The reason may be manual modification of the file.
        ///
        ///Try to fix it or generate a new key. Generating a new key will prevent the encrypted data from being restored.
        ///
        ///Do you want to generate a new key?.
        /// </summary>
        public static string msgCannotDeserializePrivateRsaKey {
            get {
                return ResourceManager.GetString("msgCannotDeserializePrivateRsaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key has errors.
        ///
        ///Contact with administrator or generate a new key. Generating a new key will prevent the encrypted data from being restored.
        ///
        ///Do you want to generate a new key?.
        /// </summary>
        public static string msgCannotDeserializePublicRsaKey {
            get {
                return ResourceManager.GetString("msgCannotDeserializePublicRsaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current custom name already in use..
        /// </summary>
        public static string msgCustomNameInUse {
            get {
                return ResourceManager.GetString("msgCustomNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom name cannot be empty..
        /// </summary>
        public static string msgEmptyCustomName {
            get {
                return ResourceManager.GetString("msgEmptyCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login cannot be empty..
        /// </summary>
        public static string msgEmptyLogin {
            get {
                return ResourceManager.GetString("msgEmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string msgEmptyPassword {
            get {
                return ResourceManager.GetString("msgEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already in use..
        /// </summary>
        public static string msgLoginInUse {
            get {
                return ResourceManager.GetString("msgLoginInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key to encrypt data was not found ({0}). 
        ///
        ///If you log in to a new location, you should move the file from the previous device.
        ///
        ///If you do not have a copy of the file, you will need to generate a new set of keys which will result in the loss of access to data on this and other devices.
        ///
        ///Continue?.
        /// </summary>
        public static string msgPrivateRsaNotFound {
            get {
                return ResourceManager.GetString("msgPrivateRsaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key for data encryption was not found. It will be necessary to generate a new set of keys which will result in the loss of access to data.
        ///
        ///Continue?.
        /// </summary>
        public static string msgPublicRsaNotFound {
            get {
                return ResourceManager.GetString("msgPublicRsaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption and decryption keys do not match.
        ///
        ///Try to fix them or generate a new key set. Generating new keys will prevent encrypted data from being restored.
        ///
        ///Do you want to generate a new key set?.
        /// </summary>
        public static string msgRsaKeysNotMatch {
            get {
                return ResourceManager.GetString("msgRsaKeysNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server with this login has already added..
        /// </summary>
        public static string msgServerExist {
            get {
                return ResourceManager.GetString("msgServerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New settings require restart the application.
        ///
        ///Do you want to restart the application?.
        /// </summary>
        public static string msgSettingsRequireRestartApplication {
            get {
                return ResourceManager.GetString("msgSettingsRequireRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test completed successfully..
        /// </summary>
        public static string msgTestConnectionConnected {
            get {
                return ResourceManager.GetString("msgTestConnectionConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example text..
        /// </summary>
        public static string testText {
            get {
                return ResourceManager.GetString("testText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About..
        /// </summary>
        public static string ttAbout {
            get {
                return ResourceManager.GetString("ttAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File..
        /// </summary>
        public static string ttAddFile {
            get {
                return ResourceManager.GetString("ttAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder..
        /// </summary>
        public static string ttAddFolder {
            get {
                return ResourceManager.GetString("ttAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all selected files and folders..
        /// </summary>
        public static string ttHideAllSelectedElements {
            get {
                return ResourceManager.GetString("ttHideAllSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options..
        /// </summary>
        public static string ttOptions {
            get {
                return ResourceManager.GetString("ttOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh..
        /// </summary>
        public static string ttRefresh {
            get {
                return ResourceManager.GetString("ttRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned servers..
        /// </summary>
        public static string ttServers {
            get {
                return ResourceManager.GetString("ttServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all hidden files and folders.
        /// </summary>
        public static string ttShowAllHiddenElements {
            get {
                return ResourceManager.GetString("ttShowAllHiddenElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume application working..
        /// </summary>
        public static string ttStart {
            get {
                return ResourceManager.GetString("ttStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop application working..
        /// </summary>
        public static string ttStop {
            get {
                return ResourceManager.GetString("ttStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization status..
        /// </summary>
        public static string ttSynchronizationStatus {
            get {
                return ResourceManager.GetString("ttSynchronizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string WindowTitleAddAccount {
            get {
                return ResourceManager.GetString("WindowTitleAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server.
        /// </summary>
        public static string WindowTitleAddServer {
            get {
                return ResourceManager.GetString("WindowTitleAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server list.
        /// </summary>
        public static string WindowTitleServers {
            get {
                return ResourceManager.GetString("WindowTitleServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string WindowTitleSettings {
            get {
                return ResourceManager.GetString("WindowTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string WindowTitleSignIn {
            get {
                return ResourceManager.GetString("WindowTitleSignIn", resourceCulture);
            }
        }
    }
}
