//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSync.AppResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSync.AppResources.Localization.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsWindowTitle {
            get {
                return ResourceManager.GetString("AccountsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSync.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAddAccount {
            get {
                return ResourceManager.GetString("btnAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEditAccount {
            get {
                return ResourceManager.GetString("btnEditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btnRemoveAccount {
            get {
                return ResourceManager.GetString("btnRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string btnSuspend {
            get {
                return ResourceManager.GetString("btnSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string btnTestConnection {
            get {
                return ResourceManager.GetString("btnTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom name.
        /// </summary>
        public static string colCustomName {
            get {
                return ResourceManager.GetString("colCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string colLogin {
            get {
                return ResourceManager.GetString("colLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string colServerName {
            get {
                return ResourceManager.GetString("colServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string colSuspended {
            get {
                return ResourceManager.GetString("colSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnumAppLanguageEnglish {
            get {
                return ResourceManager.GetString("EnumAppLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string EnumAppLanguagePolish {
            get {
                return ResourceManager.GetString("EnumAppLanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string enumServerGoogle {
            get {
                return ResourceManager.GetString("enumServerGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality is currently not available..
        /// </summary>
        public static string errNotImplementedException {
            get {
                return ResourceManager.GetString("errNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string ErrorFieldIsEmpty {
            get {
                return ResourceManager.GetString("ErrorFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string lblAppLanguage {
            get {
                return ResourceManager.GetString("lblAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Name :.
        /// </summary>
        public static string lblCustomName {
            get {
                return ResourceManager.GetString("lblCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login :.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server :.
        /// </summary>
        public static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account was not added because an identical account has already exist..
        /// </summary>
        public static string msgAccountDuplication {
            get {
                return ResourceManager.GetString("msgAccountDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with this login has already added..
        /// </summary>
        public static string msgAccountExist {
            get {
                return ResourceManager.GetString("msgAccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current custom name already in use..
        /// </summary>
        public static string msgCustomNameInUse {
            get {
                return ResourceManager.GetString("msgCustomNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom name cannot be empty..
        /// </summary>
        public static string msgEmptyCustomName {
            get {
                return ResourceManager.GetString("msgEmptyCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login cannot be empty..
        /// </summary>
        public static string msgEmptyLogin {
            get {
                return ResourceManager.GetString("msgEmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string msgEmptyPassword {
            get {
                return ResourceManager.GetString("msgEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New settings require restart the application.
        ///
        ///Do you want to restart the application?.
        /// </summary>
        public static string msgSettingsRequireRestartApplication {
            get {
                return ResourceManager.GetString("msgSettingsRequireRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test completed successfully..
        /// </summary>
        public static string msgTestConnectionConnected {
            get {
                return ResourceManager.GetString("msgTestConnectionConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About..
        /// </summary>
        public static string ttAbout {
            get {
                return ResourceManager.GetString("ttAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts..
        /// </summary>
        public static string ttAccounts {
            get {
                return ResourceManager.GetString("ttAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File..
        /// </summary>
        public static string ttAddFile {
            get {
                return ResourceManager.GetString("ttAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder..
        /// </summary>
        public static string ttAddFolder {
            get {
                return ResourceManager.GetString("ttAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all selected files and folders..
        /// </summary>
        public static string ttHideAllSelectedElements {
            get {
                return ResourceManager.GetString("ttHideAllSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options..
        /// </summary>
        public static string ttOptions {
            get {
                return ResourceManager.GetString("ttOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh..
        /// </summary>
        public static string ttRefresh {
            get {
                return ResourceManager.GetString("ttRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all hidden files and folders.
        /// </summary>
        public static string ttShowAllHiddenElements {
            get {
                return ResourceManager.GetString("ttShowAllHiddenElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume application working..
        /// </summary>
        public static string ttStart {
            get {
                return ResourceManager.GetString("ttStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop application working..
        /// </summary>
        public static string ttStop {
            get {
                return ResourceManager.GetString("ttStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization status..
        /// </summary>
        public static string ttSynchronizationStatus {
            get {
                return ResourceManager.GetString("ttSynchronizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned accounts.
        /// </summary>
        public static string WindowTitleAccounts {
            get {
                return ResourceManager.GetString("WindowTitleAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user account.
        /// </summary>
        public static string WindowTitleAddAccount {
            get {
                return ResourceManager.GetString("WindowTitleAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string WindowTitleSettings {
            get {
                return ResourceManager.GetString("WindowTitleSettings", resourceCulture);
            }
        }
    }
}
